package mapper;

import java.util.Date;
import java.util.List;
import java.util.Map;

import model.Student;
import org.apache.ibatis.annotations.Select;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Sep 30 21:00:56 CST 2020
     */
    int insert(Student student);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed Sep 30 21:00:56 CST 2020
     */
    List<Student> selectAll();

    int selectTotal();

    int delete(Integer sno);

    int deleteMany(String [] ids);

    void update(Student student);

    void updateAll(Student student);

    Student selectSno(Integer sno);

    List<Student> selectName(String name);

    @Select("select * from student where dormitory = #{dormitory}")
    List<Student> selectDormStudent(String dormitory);

    List<Student> selectDormitory(String dormitory);

    Student select_sno(Integer sno);

    List<Map<String,Object>> findStudentObject();

}