package mapper;

import java.util.List;
import model.User;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Sep 30 21:00:56 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Wed Sep 30 21:00:56 CST 2020
     */
    List<User> selectAll();

    User select(String username);


    void update(User user);

    void updateAll(User user);

    void updatepassword(String  username,String  password);


}